<%@ Page Title="" Language="C#" MasterPageFile="~/Default.Master" AutoEventWireup="true" CodeBehind="AboutTheSchoolPage.aspx.cs" Inherits="YaleArt_ttomczak3.WebForm2" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <section class="row">
        <h2>About The School</h2>
        <section class="item">
            <h3>The Yale School of Art is a graduate school that confers Master of Fine Arts Degrees in Graphic Design, Painting/Printmaking, Photography, and Sculpture</h3>
            <p>
                Artists and designers of unusual promise and strong motivation are provided an educational
                context in which they can explore the potential of their own talents in the midst of an intense
                critical dialogue. This dialogue is generated by their peers, by distinguished visitors,
                and by a faculty comprised of professional artists of acknowledged accomplishment.
            </p>
            <p>
                The graduate student’s primary educational experience at Yale is centered on the
                student’s own studio activity. Supporting this enterprise are the experience,
                knowledge, and skills gained from rigorous, structured courses such as drawing,
                filmmaking, the relativity of color, and the rich academic offerings found throughout
                Yale. Each student is routinely exposed to many aesthetic positions through encounters
                with faculty members and visitors. The School is devoted not only to the refinement of
                visual skills, but also to the cultivation of the mind. Students must bring creative force
                and imagination to their own development, for these qualities cannot be taught—they can only be stimulated and appreciated.
            </p>
            <p>
                The School of Art offers an undergraduate art major for students in Yale College
                (see the bulletin Yale College Programs of Study). In addition, the School’s courses
                are open to students in the Graduate School of Arts and Sciences and other professional
                schools of the University, and School of Art students may enroll in elective courses
                in the Graduate School and other professional schools as well as in the College with permission.
            </p>
        </section>
    </section>
</asp:Content>
